//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ключ.
    /// </summary>
    // *** Start programmer edit section *** (Ключ CustomAttributes)

    // *** End programmer edit section *** (Ключ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлючE", new string[] {
            "СгенКлюч as \'Сгенерированный ключ \'",
            "Уведомление as \'Уведомление\'",
            "ФИО as \'ФИО пользователя\'",
            "НомерПосылки as \'Номер посылки\'",
            "НомерТелефона as \'Номер телефона пользователя\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'",
            "Хранение as \'Хранение\'",
            "Хранение.Продления as \'Продления\'",
            "Хранение.ДатаНачала as \'Дата начала хранения\'",
            "Хранение.ДатаЗавершения as \'Дата завершения хранения\'"}, Hidden=new string[] {
            "Пользователь.ФИО",
            "Хранение.Продления"})]
    [MasterViewDefineAttribute("КлючE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("КлючE", "Хранение", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Продления")]
    public class Ключ : IIS.Postamat17.Уведомление
    {
        
        private IIS.Postamat17.Пользователь fПользователь;
        
        private IIS.Postamat17.БазаКлючей fБазаКлючей;
        
        // *** Start programmer edit section *** (Ключ CustomMembers)

        // *** End programmer edit section *** (Ключ CustomMembers)

        
        /// <summary>
        /// СгенКлюч.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.СгенКлюч CustomAttributes)

        // *** End programmer edit section *** (Ключ.СгенКлюч CustomAttributes)
        public override int СгенКлюч
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get start)
                int result = base.СгенКлюч;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set start)
                base.СгенКлюч = value;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set end)
            }
        }
        
        /// <summary>
        /// Ключ.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Ключ.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Postamat17.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Get start)

                // *** End programmer edit section *** (Ключ.Пользователь Get start)
                IIS.Postamat17.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Ключ.Пользователь Get end)

                // *** End programmer edit section *** (Ключ.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Set start)

                // *** End programmer edit section *** (Ключ.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Ключ.Пользователь Set end)

                // *** End programmer edit section *** (Ключ.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Postamat17.БазаКлючей.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.БазаКлючей CustomAttributes)

        // *** End programmer edit section *** (Ключ.БазаКлючей CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "БазаКлючей"})]
        public virtual IIS.Postamat17.БазаКлючей БазаКлючей
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.БазаКлючей Get start)

                // *** End programmer edit section *** (Ключ.БазаКлючей Get start)
                IIS.Postamat17.БазаКлючей result = this.fБазаКлючей;
                // *** Start programmer edit section *** (Ключ.БазаКлючей Get end)

                // *** End programmer edit section *** (Ключ.БазаКлючей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.БазаКлючей Set start)

                // *** End programmer edit section *** (Ключ.БазаКлючей Set start)
                this.fБазаКлючей = value;
                // *** Start programmer edit section *** (Ключ.БазаКлючей Set end)

                // *** End programmer edit section *** (Ключ.БазаКлючей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлючE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлючE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлючE", typeof(IIS.Postamat17.Ключ));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Ключ.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКлюч CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКлюч CustomAttributes)
    public class DetailArrayOfКлюч : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Postamat17.DetailArrayOfКлюч members)

        // *** End programmer edit section *** (IIS.Postamat17.DetailArrayOfКлюч members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Ключ by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Ключ.
        /// </summary>
        public DetailArrayOfКлюч(IIS.Postamat17.БазаКлючей fБазаКлючей) : 
                base(typeof(Ключ), ((ICSSoft.STORMNET.DataObject)(fБазаКлючей)))
        {
        }
        
        public IIS.Postamat17.Ключ this[int index]
        {
            get
            {
                return ((IIS.Postamat17.Ключ)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Postamat17.Ключ dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
