//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Принята CustomAttributes)

        // *** End programmer edit section *** (Статус.Принята CustomAttributes)
        [Caption("Принята")]
        Принята,
        
        // *** Start programmer edit section *** (Статус.Доставляется CustomAttributes)

        // *** End programmer edit section *** (Статус.Доставляется CustomAttributes)
        [Caption("Доставляется")]
        Доставляется,
        
        // *** Start programmer edit section *** (Статус.Доставлена CustomAttributes)

        // *** End programmer edit section *** (Статус.Доставлена CustomAttributes)
        [Caption("Доставлена")]
        Доставлена,
    }
}
