//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ячейки.
    /// </summary>
    // *** Start programmer edit section *** (Ячейки CustomAttributes)

    // *** End programmer edit section *** (Ячейки CustomAttributes)
    public enum Ячейки
    {
        
        // *** Start programmer edit section *** (Ячейки.Открыто CustomAttributes)

        // *** End programmer edit section *** (Ячейки.Открыто CustomAttributes)
        [Caption("Открыто")]
        Открыто,
        
        // *** Start programmer edit section *** (Ячейки.Закрыто CustomAttributes)

        // *** End programmer edit section *** (Ячейки.Закрыто CustomAttributes)
        [Caption("Закрыто")]
        Закрыто,
    }
}
